-- MySQL Script generated by MySQL Workbench
-- Thu Feb 18 14:17:23 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`admin` ;

CREATE TABLE IF NOT EXISTS `mydb`.`admin` (
  `admin_id` INT NOT NULL,
  `admin_lastname` VARCHAR(25) NOT NULL,
  `admin_firstname` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`admin_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`application`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`application` ;

CREATE TABLE IF NOT EXISTS `mydb`.`application` (
  `application_number` INT NOT NULL,
  `application_status` VARCHAR(10) NULL DEFAULT NULL,
  `application_date` DATETIME NULL DEFAULT NULL,
  `date_of_approval` DATETIME NULL DEFAULT NULL,
  `approved_by` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`application_number`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`faculty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`faculty` ;

CREATE TABLE IF NOT EXISTS `mydb`.`faculty` (
  `faculty_id` INT NOT NULL,
  `faculty_firstname` VARCHAR(25) NULL DEFAULT NULL,
  `faculty_flastname` VARCHAR(25) NULL DEFAULT NULL,
  `department` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`faculty_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`internships`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`internships` ;

CREATE TABLE IF NOT EXISTS `mydb`.`internships` (
  `employer_name` VARCHAR(25) NOT NULL,
  `duration` VARCHAR(10) NULL DEFAULT NULL,
  `start_date` DATETIME NULL DEFAULT NULL,
  `end_date` DATETIME NULL DEFAULT NULL,
  `employer_location` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`employer_name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`student` ;

CREATE TABLE IF NOT EXISTS `mydb`.`student` (
  `student_id` INT NOT NULL,
  `student_lastname` VARCHAR(25) NULL,
  `student_firstname` VARCHAR(25) NULL,
  `student_location` VARCHAR(20) NULL,
  `major` VARCHAR(25) NULL,
  `919Number` INT NULL,
  `semester` VARCHAR(10) NULL,
  `graduation` VARCHAR(10) NULL,
  PRIMARY KEY (`student_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
